spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sms:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      templateId: 908e94ccf08b4476ba6c876d13f084ad
      smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
      appcode: 1164b40dfeed466caa9d8f67b49dd114
  application:
    name: gulimall-third-party

  redis:
    host: 192.168.238.100
server:
  port: 13000
logging:
  level:
    com.atguigu.gulimall: debug




